[package]
name = "kardashev"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl2 = { version = "0.37.0", features = ["unsafe_textures"] }
gl = "0.13.0"
glam = "0.30.1"
noise = "0.8"

[dev-dependencies]
